apiVersion: v1
kind: Secret
metadata:
  name: aap-admin-password
  namespace: aap
type: Opaque
stringData:
  password: CHANGEME  # Set your AAP admin password
---
apiVersion: aap.ansible.com/v1alpha1
kind: AnsibleAutomationPlatform
metadata:
  name: aap
  namespace: aap
spec:
  admin_password_secret: aap-admin-password
  eda:
    automation_server_url: "http://aap/api/controller"
